check host requirements

diff --git a/build b/build
--- a/build
+++ b/build
@@ -8,13 +8,50 @@ if [ ! $(whoami) = "root"  ]; then
 fi
 
 check() {
+	# https://www.linuxfromscratch.org/lfs/view/stable/chapter02/hostreqs.html
+	bash --version | head -n1 | cut -d" " -f2-4
+	MYSH=$(readlink -f /bin/sh)
+	echo "/bin/sh -> $MYSH"
+	echo $MYSH | grep -q bash || echo "ERROR: /bin/sh does not point to bash"
+	unset MYSH
+	
+	echo -n "Binutils: "; ld --version | head -n1 | cut -d" " -f3-
+	bison --version | head -n1
+	
+	if [ -h /usr/bin/yacc ]; then
+	  echo "/usr/bin/yacc -> `readlink -f /usr/bin/yacc`";
+	elif [ -x /usr/bin/yacc ]; then
+	  echo yacc is `/usr/bin/yacc --version | head -n1`
+	else
+	  echo "yacc not found"
+	fi
+	
+	echo -n "Coreutils: "; chown --version | head -n1 | cut -d")" -f2
+	diff --version | head -n1
+	find --version | head -n1
+	gawk --version | head -n1
+	
+	if [ -h /usr/bin/awk ]; then
+	  echo "/usr/bin/awk -> `readlink -f /usr/bin/awk`";
+	elif [ -x /usr/bin/awk ]; then
+	  echo awk is `/usr/bin/awk --version | head -n1`
+	else
+	  echo "awk not found"
+	fi
+	
+	gcc --version | head -n1
 	apt-get --version | head -n1
 	grep --version | head -n1
 	gzip --version | head -n1
+	m4 --version | head -n1
+	make --version | head -n1
 	patch --version | head -n1
 	sed --version | head -n1
 	tar --version | head -n1
+	makeinfo --version | head -n1
 	xz --version | head -n1
+
+	
 }
 
 getsources() {
